/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"STM32F103C6_GPIO_DRIVER.h"
#include"STM32F103X6.h"
#include"KEYPAD.h"
#include"lcd.h"
#include"STM32F103C6_EXTI_DRIVER.h"

unsigned int IRQ_FLAG=0;

void Clock_init(){
	//ENABLE CLOCK GPIOA
	RCC_GPIOA_CLK_EN();
	//ENABLE CLOCK GPIOB
	RCC_GPIOB_CLK_EN();
	AFIO_CLK_EN();


}
void wait_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}

void EXTI9_CALLING(void){
	IRQ_FLAG=1;
	LCD_WRITE_STRING("IRQ_EXTI9 IS HAPPEN -|-");
	wait_ms(1000);
}



int main(){
	Clock_init();
	LCD_INIT();
	LCD_CLEAR_SCREEN();


EXTI_PINCONFIG_t EX;
EX.EXTI_PIN=EXTI9_PB9;
EX.TRIGGER_CASE=EXTI_TRIGGER_RISING;
EX.P_IRQ_CALLBACK= EXTI9_CALLING;
EX.IRQ_STATE=EXTI_IRQ_ENABLE;
MCAL_EXTI_GPIO_INIT(&EX);
IRQ_FLAG=1;

	while(1){
		if(IRQ_FLAG){
		LCD_CLEAR_SCREEN();
		IRQ_FLAG=0;
		}
	}

}
