/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//RCC ADDRESS
#define RCC_BASE   0x40021000
#define RCC_APB2ENR	*(volatile uint32_t*) (RCC_BASE+0x18)
#define RCC_IOPAEN	(1<<2)
//GPIO ADDRESS
#define GPIO_BASE	0x40010800
#define GPIO_CRH    *(volatile uint32_t*) (GPIO_BASE+0x04)
#define GPIO_CRL    *(volatile uint32_t*) (GPIO_BASE+0x00)
#define GPIO_ODR    *(volatile uint32_t*) (GPIO_BASE+0x0C)
#define GPIO13	    (1UL<<13)

//EXTI ADDRESS
#define EXTI_BASE 0x40010400
#define EXTI_IMR    *(volatile uint32_t*) (EXTI_BASE+0x00)
#define EXTI_RTSR   *(volatile uint32_t*) (EXTI_BASE+0x08)
#define EXTI_PR		*(volatile uint32_t*) (EXTI_BASE+0x14)

//AFIO ADDRESS
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t*) (AFIO_BASE+0x08)

//NVIC ADDRESS
#define NVIC_EXTIEN0	*(volatile uint32_t*) (0xE000E100)



void Clock_init(){
	RCC_APB2ENR|= RCC_IOPAEN; //to set 1 bit
	//Bit 0 AFIOEN: Alternate function IO clock enable
	RCC_APB2ENR	|=(1<<0);

}
void GPIO_init(){
	GPIO_CRH	&= 0xFF0FFFFF;  //make 4 bit as to or with 2 (in binary 0010) in next step
	GPIO_CRH	|= 0x00200000;
	GPIO_CRL	|=(1<<2);       //PINA INPUT FLOATING
}

int main(void)
{
	Clock_init();
	GPIO_init();
	//ENABLE EXTI LINE 0 ?? --> BY LET MASK ENABLE REGISTER EQUAL 1
	EXTI_IMR |= (1<<0);

	//RISING TRIGGER SELECTION REQISTER EQUAL 1
	EXTI_RTSR |= (1<<0);

	//TO CLEAR PENDING  REQUEST
	EXTI_PR |= (1<<0);

	// CHOICE PORTA FROM EXTI LINE 0
	AFIO_EXTICR1 |= (0b0000<<0);

	//ENABLE NVIC IRQ6 --> EXTI0
	NVIC_EXTIEN0 |= (1<<6);


	while(1);
	}
void EXTI0_IRQHandler(void ){
	//IRQHandler IS HAPPENED EXTI0>>>> PORTA -> PIN 0 IN RISING EDGE
	//TOGGLE LED PIN A ->13
	GPIO_ODR	^= (1<<13);
}
