/*
 * STM103C6_HEADERS.H
 *
 *  Created on: Jul 7, 2023
 *      Author: King 45M
 */

#ifndef INC_STM103C6_HEADERS_H_
#define INC_STM103C6_HEADERS_H_

#include "STM32F103X6.h"
#include "STM32F103C6_EXTI_DRIVER.h"
#include "STM32F103C6_GPIO_DRIVER.h"
#include "STM32F103C6_RCC_DRIVER.h"
#include "STM32F103C6_USART_DRIVER.h"
#include "STM32F103C6_SPI_DRIVER.h"
#include "STM32F103C6_I2C_DRIVER.h"
#include "EEPROM.h"
#include<stdlib.h>
#include<stdio.h>
#include<stdint.h>


#endif /* INC_STM103C6_HEADERS_H_ */
