/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM103C6_HEADERS.H"


unsigned int CH;

void Clock_init(){
	//ENABLE CLOCK GPIOA
	RCC_GPIOA_CLK_EN();
	//ENABLE CLOCK GPIOB
	RCC_GPIOB_CLK_EN();
	AFIO_CLK_EN();


}
/*void wait_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}


void EXTI9_CALLING(void){
	IRQ_FLAG=1;
	LCD_WRITE_STRING("IRQ_EXTI9 IS HAPPEN -|-");
	wait_ms(1000);
}

*/
void UART_IRQ_Callback (void){
	MCAL_USART_RECIEVE(USART1, &CH, disable);
	MCAL_USART_SEND(USART1, &CH, enable);

}
int main(){
	Clock_init();
	USART_CONFIG uartCFG ;
	uartCFG.USART_BAUDRATE = USART_BAUDRATE_115200 ;
	uartCFG.USART_FLOWCTL = USART_FLOWCTL_NONE ;
	uartCFG.USART_IRQHANDLER = USART_IRQ_ENABLE_RXNE ;
	uartCFG.P_IRQ_CALLBACK =UART_IRQ_Callback ;
	uartCFG.USART_PARITY=USART_PARITY_NONE ;
	uartCFG.USART_PAYLOAD_LENGHTH = USART_PAYLOAD_LENGHTH8B;
	uartCFG.USART_STOPBITS = USART_STOPBITS_ONE ;
	uartCFG.USART_MODE = USART_MODE_TX_RX ;

	MCAL_USART_INIT(USART1, &uartCFG);
	MCAL_USART_GPIO_SETPIN(USART1);

	while(1){


	}

}
