/*
 * EEPROM.c
 *
 *  Created on: Aug 24, 2023
 *      Author: ANDREW NASSER
 */

#include "STM103C6_HEADERS.H"

void EEPROM_INIT(void)
{
	I2C_CONFIG I2C_CNFG;
	I2C_CNFG.I2C_ACK=I2C_ACK_ENABLE; ;
	I2C_CNFG.IRQ_EN =I2C_IRQ_ENABLE_DISABLE ;
	I2C_CNFG.NUM_ADDRESS_BIT=I2C_7BIT_SLAVE_MODE_ADD ;
	I2C_CNFG.I2C_CLCK_SPEED=I2C_CLCK_SM_100K;
	MCAL_I2C_GPIO_SETPIN(I2C1);
	MCAL_I2C_INIT(I2C1, &I2C_CNFG);
}


unsigned char EEPROM_WRITE_DATA(uint32_t EEPROM_ADDRESS , uint8_t* PTXBUFFER , uint8_t DATALEN)
{
	uint8_t i=0;
	uint8_t BUFFER[256];
	BUFFER[0] = (uint8_t)(EEPROM_ADDRESS>>8);   // TO SEND UPPER BYTE
	BUFFER[1] = (uint8_t)(EEPROM_ADDRESS);		// TO SEND LOWER BYTE

	for( i =2 ; i<(DATALEN+2) ; i++)
	{
		BUFFER[i]= PTXBUFFER[i-2];
	}

	MCAL_I2C_MASTER_TX(I2C1, EEPROM_SLAVE_ADRESS, BUFFER, (DATALEN+2), WITHOUT_STOP, START);

	return 0;
}

unsigned char EEPROM_READ_DATA( uint32_t EEPROM_ADDRESS , uint8_t* PRXBUFFER , uint8_t DATALEN)
{
	uint8_t BUFFER[2];
	BUFFER[0] = (uint8_t)(EEPROM_ADDRESS>>8);   // TO SEND UPPER BYTE
	BUFFER[1] = (uint8_t)(EEPROM_ADDRESS);		// TO SEND LOWER BYTE
	//send address
	MCAL_I2C_MASTER_TX(I2C1, EEPROM_SLAVE_ADRESS, BUFFER, 2, WITHOUT_STOP, START);
	// Read Data
	MCAL_I2C_MASTER_RX(I2C1, EEPROM_SLAVE_ADRESS, PRXBUFFER, DATALEN, WITHOUT_STOP, REPEATEDSTART);

	return 0;
}
