/*
 * lcd.c
 *
 * Created: 4/20/2023 3:01:25 PM
 *  Author: ANDREW NASSER
 */

#include "STM103C6_HEADERS.H"
GPIO_PINCONFIG_T PINCFG ;

void delay_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}

void LCD_GPIO_init() {
	PINCFG.GPIO_PIN_NUMBER  = RS_SWITCH;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT = GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = RW_SWITCH;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = EN_SWITCH;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	//============================
	// SET THE NEXT 8 PINS AS INPUT
	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN0;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN1;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN2;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN3;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN4;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN5;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT = GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN6;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN7;
	PINCFG.GPIO_MODE = GPIO_MODE_PUSH_PULL;
	PINCFG.GPIO_SPEED_OUTPUT= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	MCAL_GPIO_WRITEPIN(LCD_CTRL, EN_SWITCH, GPIO_PIN_RESET);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RS_SWITCH, GPIO_PIN_RESET);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RW_SWITCH, GPIO_PIN_RESET);

}

void LCD_CLEAR_SCREEN() {
	LCD_WRITE_COMMAND(LCD_Clear_Display);
}

void LCD_KICK() {
	MCAL_GPIO_WRITEPIN(LCD_CTRL, EN_SWITCH, GPIO_PIN_SET);
	delay_ms(50);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, EN_SWITCH, GPIO_PIN_RESET);
}

void LCD_GOTO_XY(unsigned char line, unsigned char position) {
	if (line == 1) {
		if (position < 16 && position >= 0) {
			LCD_WRITE_COMMAND(LCD_ROW1_COLUMN1+ position);
		}
	}
	if (line == 2) {
		if (position < 16 && position >= 0) {
			LCD_WRITE_COMMAND(LCD_ROW2_COLUMN2 + position);
		}
	}
}

void LCD_INIT() {

	delay_ms(20);
	// SET THE FIRST 3 PINS AS OUPUT
	LCD_GPIO_init();

	delay_ms(15);
	LCD_WRITE_COMMAND(LCD_Return_Home);
	LCD_CLEAR_SCREEN();
	LCD_WRITE_COMMAND(LCD_8BITS_2LINES_5X8);
	LCD_WRITE_COMMAND(LCD_Enty_Mode_Set_Inc);
	LCD_WRITE_COMMAND(LCD_ROW1_COLUMN1);
	LCD_WRITE_COMMAND(LCD_DISP_ON_CURSOR_BLINK);
}

void LCD_CHECK_BUSY() {
	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN0;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN1;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN2;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN3;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN4;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN5;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN6;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	PINCFG.GPIO_PIN_NUMBER  = GPIO_PIN7;
	PINCFG.GPIO_MODE = GPIO_MODE_FLOATING;
	MCAL_GPIO_INIT(LCD_CTRL,  &PINCFG);

	MCAL_GPIO_WRITEPIN(LCD_CTRL, RW_SWITCH, GPIO_PIN_SET);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RS_SWITCH, GPIO_PIN_RESET);
//	LCD_CTRL |= (1 << RW_SWITCH);
//	LCD_CTRL &= ~(1 << RS_SWITCH);
	LCD_KICK();
//	DataDir_LCD_PORT |= (0xFF << DATA_shift);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RW_SWITCH, GPIO_PIN_RESET);
//	LCD_CTRL &= ~(1 << RW_SWITCH);

}

void LCD_WRITE_COMMAND(unsigned char command) {
//	LCD_check_lcd_isbusy();
	MCAL_GPIO_WRITEPORT(LCD_CTRL, command);
//	LCD_CTRL->BRR = (LCD_CTRL->BRR & 0x00FF) | (command);
//	LCD_CTRL->CRL ^= (LCD_CTRL->CRL ^ command) & 0x00ff;
//	LCD_CTRL->CRL = command;
//	LCD_CTRL ^= (LCD_CTRL-> ^ command) & 0x00ff;
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RW_SWITCH, GPIO_PIN_RESET);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RS_SWITCH, GPIO_PIN_RESET);
//	LCD_CTRL &= ~((1 << RS_SWITCH) | (1<<RW_SWITCH));
	delay_ms(1);
	LCD_KICK();

}

void LCD_WRITE_CHAR(unsigned char character) {
//	LCD_check_lcd_isbusy();
//	LCD_CTRL->CRL = character;
//	LCD_CTRL->CRL ^= (LCD_CTRL->CRL ^ character) & 0x00ff;
	MCAL_GPIO_WRITEPORT(LCD_CTRL, character);
//	LCD_CTRL ^= (LCD_CTRL ^ character) & 0x00ff;
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RW_SWITCH, GPIO_PIN_RESET);
	MCAL_GPIO_WRITEPIN(LCD_CTRL, RS_SWITCH, GPIO_PIN_SET);
//	LCD_CTRL &= ~(1 << RW_SWITCH);
//	LCD_CTRL |= (1 << RS_SWITCH);
	delay_ms(1);
	LCD_KICK();
}

void LCD_WRITE_STRING(char *string) {
	int count = 0;
	while (*string > 0) {
		count++;
		LCD_WRITE_CHAR(*string++);
		if (count == 16) {
			LCD_GOTO_XY(2, 0);
		} else if (count == 32) {
			LCD_CLEAR_SCREEN();
			LCD_GOTO_XY(1, 0);
			count = 0;
		}
	}
}
